# Generated by Django 2.0.7 on 2019-01-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190121_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auth_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
