# Generated by Django 2.1.5 on 2019-01-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('rater_number', models.PositiveIntegerField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
            options={
                'verbose_name_plural': 'Item Ratings',
            },
        ),
    ]
