# Generated by Django 2.1.5 on 2019-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190127_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
