# Generated by Django 2.1.5 on 2019-01-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transactionitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='review_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.Item'),
        ),
    ]
